### Recuperar todas las películas 
GET http://localhost:1234/movies

### Recuperar una películas por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las peliculas por un género
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json


 {
  "title": "Pulp Fiction",
  "year": 1994,
  "director": "Quentin Tarantino",
  "duration": 154,
  "poster": "https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
  "rate": 8.9,
  "genre": ["Crime", "Drama"]
}

### borrar una pelicula
DELETE http://localhost:1234/movies/8a233c3a-0ced-48f5-ae93-0474d6a94a24

### Actualizar una pelicula  una parte 
PATCH http://localhost:1234/movies/59bb45bc-622b-11f1-b9b9-7a73624f9fe9
Content-Type: application/json


  {
  "year": 2011,
  "rate": 9.5
}

